
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x0b#f\xe9I\xf1\x94D\x80\xf4\xa7\xea\\MD~'
    
_lr_action_items = {'NODE':([0,1,2,3,4,5,9,10,11,12,13,15,16,17,18,19,20,21,22,],[2,-6,-3,-5,2,-4,2,2,2,2,2,2,-9,-12,-8,-11,-10,-13,-7,]),'REGEX':([0,1,2,3,4,5,9,10,11,12,13,14,15,16,17,18,19,20,21,22,],[1,-6,-3,-5,1,-4,1,1,1,1,1,21,1,-9,-12,-8,-11,-10,-13,-7,]),'GT':([1,2,3,5,7,],[-6,-3,-5,-4,9,]),'GE':([1,2,3,5,7,],[-6,-3,-5,-4,11,]),'STRING':([0,1,2,3,4,5,9,10,11,12,13,15,16,17,18,19,20,21,22,],[3,-6,-3,-5,3,-4,3,3,3,3,3,3,-9,-12,-8,-11,-10,-13,-7,]),'REQ':([1,2,3,5,7,],[-6,-3,-5,-4,14,]),'NUMBER':([0,1,2,3,4,5,9,10,11,12,13,15,16,17,18,19,20,21,22,],[5,-6,-3,-5,5,-4,5,5,5,5,5,5,-9,-12,-8,-11,-10,-13,-7,]),'LT':([1,2,3,5,7,],[-6,-3,-5,-4,12,]),'LE':([1,2,3,5,7,],[-6,-3,-5,-4,13,]),'IN':([1,2,3,5,7,],[-6,-3,-5,-4,10,]),'EQ':([1,2,3,5,7,],[-6,-3,-5,-4,15,]),'$end':([1,2,3,4,5,6,8,16,17,18,19,20,21,22,],[-6,-3,-5,-1,-4,0,-2,-9,-12,-8,-11,-10,-13,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,],[4,4,]),'statement':([0,4,],[6,8,]),'factor':([0,4,9,10,11,12,13,15,],[7,7,16,17,18,19,20,22,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',104),
  ('statement -> expression statement','statement',2,'p_statement_recursive','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',110),
  ('factor -> NODE','factor',1,'p_factor_value','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',116),
  ('factor -> NUMBER','factor',1,'p_factor_value','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',117),
  ('factor -> STRING','factor',1,'p_factor_value','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',118),
  ('factor -> REGEX','factor',1,'p_factor_regex','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',124),
  ('expression -> factor EQ factor','expression',3,'p_factor_miexd','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',129),
  ('expression -> factor GE factor','expression',3,'p_factor_miexd','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',130),
  ('expression -> factor GT factor','expression',3,'p_factor_miexd','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',131),
  ('expression -> factor LE factor','expression',3,'p_factor_miexd','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',132),
  ('expression -> factor LT factor','expression',3,'p_factor_miexd','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',133),
  ('expression -> factor IN factor','expression',3,'p_factor_in','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',147),
  ('expression -> factor REQ REGEX','expression',3,'p_factor_reg_in','/home/hitsmaxft/local/playground/Bee/Bee/BeeLang.py',158),
]
